name: Staging deployment

on: 
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    
    steps:
      - name: Checkout src
        uses: actions/checkout@v2.1.0
      - run: |
          npm install
          npm run build
      - name: Upload NPM build output
        uses: actions/upload-artifact@v2
        with:
          name: webpack artifacts
          path: public

  deploy:
    name: Deploy Node.js app to AWS
    needs: [build]
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout src
        uses: actions/checkout@v2.1.0
      - name: Download built artifact
        uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: public
      - name: Deploy to AWS
        uses: github/deploy-nodejs@master
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
